### ISSUE TITLE
pkg_resources is deprecated and no longer available for import by default as of Python 3.12.

### ISSUE THREAD

**Issue by kod-kristoff** [glenfant/stopit#39]
Major drawback for our project.

Possible solution in PR glenfant/stopit#34

**Comment by kod-kristoff** [comment]
I can confirm that the PR solves this issue.

With [`uv`](https://docs.astral.sh/uv/) you can override this dependency (for developing) by adding the PR repo under `[tool.uv.sources]` as follows:

```toml
# pyproject.toml
[project]
dependecies = ["stopit>=1.1.2"]

[tool.uv.sources]
stopit = { git = "https://github.com/jikamens/stopit", branch = "master" }
```
